version: "3.9"
services:
  db:
    image: postgres:latest
    volumes:
      - data:/var/lib/postgresql/data
    env_file: ./.env.local
    ports:
      - "6432:5432"

  db-test:
    image: postgres:latest
    env_file: ./.env.test.local
    ports:
      - 6433:5432

volumes:
  data:
