services:
  - type: web
    name: orgu
    env: node
    plan: starter
    region: frankfurt
    buildCommand: yarn --frozen-lockfile --prod=false &&
      blitz prisma generate &&
      blitz build &&
      blitz prisma migrate deploy
    startCommand: blitz start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: orgu-db
          property: connectionString
      - key: SESSION_SECRET_KEY
        generateValue: true
      - key: GITHUB_CLIENT_ID
        sync: false
      - key: GITHUB_CLIENT_SECRET
        sync: false
      - key: BASE_URL
        sync: false

databases:
  - name: orgu-db
    plan: starter
    region: frankfurt
